Preprocessing cosmetics Unify input/output defines to HAVE_* format. Define values as 1 to simplify conditionals.

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -7,10 +7,10 @@ echo ""
 echo "available options:"
 echo ""
 echo "  --help                   print this message"
-echo "  --disable-avs-input      disables avisynth input (win32 only)"
-echo "  --disable-lavf-input     disables libavformat input"
-echo "  --disable-ffms-input     disables ffmpegsource input"
-echo "  --disable-mp4-output     disables mp4 output (using gpac)"
+echo "  --disable-avs            disables avisynth support (windows only)"
+echo "  --disable-lavf           disables libavformat support"
+echo "  --disable-ffms           disables ffmpegsource support"
+echo "  --disable-gpac           disables gpac support"
 echo "  --disable-pthread        disables multithreaded encoding"
 echo "  --disable-asm            disables platform-specific assembly optimizations"
 echo "  --enable-debug           adds -g, doesn't strip"
@@ -95,7 +95,7 @@ as_check() {
 }
 
 define() {
-    echo "#define $1$([ -n "$2" ] && echo " $2")" >> config.h
+    echo "#define $1$([ -n "$2" ] && echo " $2" || echo " 1")" >> config.h
 }
 
 die() {
@@ -113,10 +113,10 @@ libdir='${exec_prefix}/lib'
 includedir='${prefix}/include'
 DEVNULL='/dev/null'
 
-avs_input="auto"
-lavf_input="auto"
-ffms_input="auto"
-mp4_output="auto"
+avs="auto"
+lavf="auto"
+ffms="auto"
+gpac="auto"
 pthread="auto"
 asm="auto"
 debug="no"
@@ -157,17 +157,17 @@ for opt do
         --disable-asm)
             asm="no"
             ;;
-        --disable-avs-input)
-            avs_input="no"
+        --disable-avs)
+            avs="no"
             ;;
-        --disable-lavf-input)
-            lavf_input="no"
+        --disable-lavf)
+            lavf="no"
             ;;
-        --disable-ffms-input)
-            ffms_input="no"
+        --disable-ffms)
+            ffms="no"
             ;;
-        --disable-mp4-output)
-            mp4_output="no"
+        --disable-gpac)
+            gpac="no"
             ;;
         --extra-asflags=*)
             ASFLAGS="$ASFLAGS ${opt#--extra-asflags=}"
@@ -504,8 +504,8 @@ else
     vis="no"
 fi
 
-if [ "$lavf_input" = "auto" ] ; then
-    lavf_input="no"
+if [ "$lavf" = "auto" ] ; then
+    lavf="no"
     if ${cross_prefix}pkg-config --exists libavformat libavcodec libswscale 2>$DEVNULL; then
         LAVF_LIBS="$LAVF_LIBS $(${cross_prefix}pkg-config --libs libavformat libavcodec libswscale)"
         LAVF_CFLAGS="$LAVF_CFLAGS $(${cross_prefix}pkg-config --cflags libavformat libavcodec libswscale)"
@@ -521,18 +521,18 @@ if [ "$lavf_input" = "auto" ] ; then
        cc_check libswscale/swscale.h "$LAVF_CFLAGS $LAVF_LIBS" ; then
         # avcodec_decode_video2 is currently the most recently added function that we use; it was added in r18351
         if cc_check libavformat/avformat.h "$LAVF_CFLAGS $LAVF_LIBS" "avcodec_decode_video2( NULL, NULL, NULL, NULL );" ; then
-            lavf_input="yes"
-            define LAVF_INPUT
+            lavf="yes"
+            define HAVE_LAVF
         else
             echo "Warning: libavformat is too old, update to ffmpeg r18351+"
         fi
     fi
 fi
 
-if [ "$ffms_input" = "auto" ] ; then
+if [ "$ffms" = "auto" ] ; then
     ffms_major="2"; ffms_minor="13"; ffms_micro="1"; ffms_bump="0"
 
-    ffms_input="no"
+    ffms="no"
     [ $ffms_micro -gt 0 -o $ffms_bump -gt 0 ] && vmicro=".$ffms_micro"
     [ $ffms_bump -gt 0 ] && vbump=".$ffms_bump"
     if ${cross_prefix}pkg-config --atleast-version="$ffms_major.$ffms_minor$vmicro$vbump" ffms2 2>$DEVNULL; then
@@ -545,13 +545,13 @@ if [ "$ffms_input" = "auto" ] ; then
     [ -z "$FFMS2_LIBS" ] && FFMS2_LIBS="-lffms2"
 
     if cc_check ffms.h "$FFMS2_CFLAGS $FFMS2_LIBS" "FFMS_DestroyVideoSource(0);" ; then
-        ffms_input="yes"
+        ffms="yes"
     elif cc_check ffms.h "$FFMS2_CFLAGS $FFMS2_LIBS -lstdc++ $LAVF_LIBS" "FFMS_DestroyVideoSource(0);" ; then
-        ffms_input="yes"
+        ffms="yes"
         FFMS2_LIBS="$FFMS2_LIBS -lstdc++ $LAVF_LIBS"
     fi
 
-    if [ $api_check = "yes" -a $ffms_input = "yes" ]; then
+    if [ $api_check = "yes" -a $ffms = "yes" ]; then
         log_check "whether ffms2 version is at least $ffms_major.$ffms_minor$vmicro$vbump"
         $CC $CFLAGS $FFMS2_CFLAGS -c -o conftest -x c - >$DEVNULL 2>&1 <<EOF
 #include <ffms.h>
@@ -559,50 +559,50 @@ if [ "$ffms_input" = "auto" ] ; then
 #error Requires ffms2 version 2.13.1
 #endif
 EOF
-        [ $? = 0 ] && log_ok || { ffms_input="no"; log_fail; }
+        [ $? = 0 ] && log_ok || { ffms="no"; log_fail; }
     fi
 fi
 
-if [ "$ffms_input" = "yes" ]; then
+if [ "$ffms" = "yes" ]; then
     LDFLAGSCLI="$FFMS2_LIBS $LDFLAGSCLI"
     [ -n "$FFMS2_CFLAGS" ] && CFLAGS="$CFLAGS $FFMS2_CFLAGS"
-    define FFMS_INPUT
-elif [ "$lavf_input" = "yes" ]; then
+    define HAVE_FFMS
+elif [ "$lavf" = "yes" ]; then
     LDFLAGSCLI="$LAVF_LIBS $LDFLAGSCLI"
     [ -n "$LAVF_CFLAGS" ] && CFLAGS="$CFLAGS $LAVF_CFLAGS"
 fi
 
-MP4_LDFLAGS="-lgpac_static"
+GPAC_LIBS="-lgpac_static"
 if [ $SYS = MINGW ]; then
-    MP4_LDFLAGS="$MP4_LDFLAGS -lwinmm"
+    GPAC_LIBS="$GPAC_LIBS -lwinmm"
 fi
-if [ "$mp4_output" = "auto" ] ; then
-    mp4_output="no"
-    if cc_check gpac/isomedia.h "$MP4_LDFLAGS" ; then
-        if cc_check gpac/isomedia.h "$MP4_LDFLAGS" "gf_isom_set_pixel_aspect_ratio(0,0,0,0,0);" ; then
-            mp4_output="yes"
+if [ "$gpac" = "auto" ] ; then
+    gpac="no"
+    if cc_check gpac/isomedia.h "$GPAC_LIBS" ; then
+        if cc_check gpac/isomedia.h "$GPAC_LIBS" "gf_isom_set_pixel_aspect_ratio(0,0,0,0,0);" ; then
+            gpac="yes"
         else
             echo "Warning: gpac is too old, update to 2007-06-21 UTC or later"
         fi
     fi
 fi
-if [ "$mp4_output" = "yes" ] ; then
-    define MP4_OUTPUT
-    if cc_check gpac/isomedia.h "-Werror $MP4_LDFLAGS" "gf_malloc(1); gf_free(NULL);" ; then
+if [ "$gpac" = "yes" ] ; then
+    define HAVE_GPAC
+    if cc_check gpac/isomedia.h "-Werror $GPAC_LIBS" "gf_malloc(1); gf_free(NULL);" ; then
         define HAVE_GF_MALLOC
     fi
-    LDFLAGSCLI="$LDFLAGSCLI $MP4_LDFLAGS"
+    LDFLAGSCLI="$LDFLAGSCLI $GPAC_LIBS"
 fi
 
-if [ "$avs_input" = "auto" ] ; then
-    avs_input=no
+if [ "$avs" = "auto" ] ; then
+    avs=no
     if [ $SYS = MINGW ] && cc_check avisynth_c.h ; then
-        avs_input="yes"
-        define AVS_INPUT
+        avs="yes"
+        define HAVE_AVS
         define HAVE_AVISYNTH_C_H
     elif [ $SYS = MINGW ] && cc_check extras/avisynth_c.h ; then
-        avs_input="yes"
-        define AVS_INPUT
+        avs="yes"
+        define HAVE_AVS
     fi
 fi
 
@@ -706,10 +706,10 @@ cat > conftest.log <<EOF
 Platform:   $ARCH
 System:     $SYS
 asm:        $asm
-avs input:  $avs_input
-lavf input: $lavf_input
-ffms input: $ffms_input
-mp4 output: $mp4_output
+avs:        $avs
+lavf:       $lavf
+ffms:       $ffms
+gpac:       $gpac
 pthread:    $pthread
 debug:      $debug
 gprof:      $gprof
