READ ONLY: Daily import from FFMPEG git
git-svn-id: https://xuggle-ffmpeg.googlecode.com/svn/trunk@936 9f8918ac-6a95-11de-be4f-b1b98ff093f4

diff --git a/ffmpeg/csrc/configure b/ffmpeg/csrc/configure
--- a/ffmpeg/csrc/configure
+++ b/ffmpeg/csrc/configure
@@ -761,7 +761,7 @@ check_pkg_config(){
     headers="$2"
     funcs="$3"
     shift 3
-    $pkg_config --exists $pkg || return
+    $pkg_config --exists $pkg 2>/dev/null || return
     pkg_cflags=$($pkg_config --cflags $pkg)
     pkg_libs=$($pkg_config --libs $pkg)
     check_func_headers "$headers" "$funcs" $pkg_cflags $pkg_libs "$@" &&
@@ -1856,6 +1856,11 @@ sysinclude_default="${sysroot}/usr/include"
 set_default cc nm pkg_config strip sysinclude
 enabled cross_compile || host_cc_default=$cc
 set_default host_cc
+
+if ! $pkg_config --version >/dev/null 2>&1; then
+    warn "$pkg_config not found, library detection may fail."
+    pkg_config=false
+fi
 
 exesuf() {
     case $1 in
