ignore non-existent patch files, and actually fail if they don't work

diff --git a/captive/ffmpeg/incarcerate.in b/captive/ffmpeg/incarcerate.in
--- a/captive/ffmpeg/incarcerate.in
+++ b/captive/ffmpeg/incarcerate.in
@@ -107,7 +107,13 @@ chmod -R u+w @abs_builddir@/csrc/*
 if [ -d @abs_srcdir@/patches ]; then
   cd @abs_builddir@/csrc
   for patch in @abs_srcdir@/patches/*; do
-    patch -p0 < "$patch" || (echo "Could not apply patch: $patch" && exit 1)
+    if [ -f "$patch" ]; then
+      patch -p0 < "$patch"
+      if [ $? -ne 0]; then
+        echo "Could not apply patch: $patch"
+        exit 255
+      fi
+    fi
   done
 fi
 
